# ${project.name} v${project.version}
# @author     ucchy
# @license    LGPLv3
# @copyright  Copyright ucchy 2015


# =============== 共通設定 ===============

# メッセージの言語
lang: ja

# 最大参加人数。少なくとも5人以上に設定してください。
maxPlayers: 64

# ゲーム内の1時間を、実際の何秒にするかを指定します。
# 例えば90にすると、1時間進むのに90秒かかり、1つのNightに9分（540秒）かかります。
secondsOfOneHour: 90

# Nightが終わって、次のNightが始まるまでの、インターバル。秒数で指定します。
secondsOfNightInterval: 15

# 1秒あたりのバッテリー基本消費量
batteryDecreasePerSecond: 0.14

# 懐中電灯を使用しているときの1秒あたりのバッテリー消費量
batteryFlashLightPerSecond: 0.2

# レーダーを使用したときの1回あたりのバッテリー消費量
batteryRaderPerUse: 1.0

# シャッターを使用しているときの1秒あたりのバッテリー消費量
batteryShutterPerSecond: 0.67

# レーダーの索敵範囲。デフォルトは15マスです。
raderSearchingRange: 15

# プレイヤーのログアウト逃げ期限時間（秒）。
# もしプレイヤーがゲーム中にログアウトし、設定時間が過ぎた場合、そのプレイヤーは負けになります。
playerLogoutTrackingSeconds: 20

# =============== Freddy's陣営の強さ設定 ===============

# Night1 の各キャラの移動速度。
# 各キャラの移動速度レベルを、-99(移動不可)か、-5から5で設定します。
# Foxyは普段は移動不可で、行動時間の時のみ、ここに設定した移動速度で移動できます。
# foxyMovementは、Foxyが一晩で行動できる回数です。-1か、0か、1から5が設定できます。
# -1を設定すると、そのNightは行動できません。0を設定すると、1から5がランダムで選択されます。
night1MoveSpeed:
  freddy: -99
  chica: -3
  bonnie: -3
  foxy: 1
  foxyMovement: 1

# Night2 の各キャラの移動速度。
night2MoveSpeed:
  freddy: -99
  chica: -2
  bonnie: -2
  foxy: 1
  foxyMovement: 1

# Night3 の各キャラの移動速度。
night3MoveSpeed:
  freddy: -1
  chica: -1
  bonnie: -1
  foxy: 2
  foxyMovement: 2

# Night4 の各キャラの移動速度。
night4MoveSpeed:
  freddy: 0
  chica: 0
  bonnie: 0
  foxy: 3
  foxyMovement: 3

# Night5 の各キャラの移動速度。
night5MoveSpeed:
  freddy: 1
  chica: 1
  bonnie: 1
  foxy: 3
  foxyMovement: 3

# Night6 の各キャラの移動速度。
night6MoveSpeed:
  freddy: 2
  chica: 2
  bonnie: 2
  foxy: 4
  foxyMovement: 4

# カスタムナイト(Night7)の各キャラの移動速度。
customNightMoveSpeed:
  freddy: 4
  chica: 4
  bonnie: 4
  foxy: 5
  foxyMovement: 5

# Foxyが、一回の行動で移動可能な時間（秒）を指定します。
foxyMovementSeconds: 15

# =============== 効果音の設定 ===============

# 懐中電灯のオンオフ
soundUseFlashLight: 'CLICK'

# レーダーの使用
soundUseRader: 'IRONGOLEM_HIT-1.0-0.7'

# シャッターの使用
soundUseShutter: 'WITHER_SHOOT-1.0-1.0'

# Foxyの行動開始
soundFoxyMovement: 'ZOMBIE_REMEDY-1.0-1.0'

# Freddyの電力切れプレイヤーへのテレポート
# この効果音はテレポート先の近隣プレイヤーに流れます。
# リソースパックで、Freddyのオルゴール音に変えるといいかも。
soundFreddyTeleport: 'ENDERMAN_TELEPORT-1.0-0.8,BLAZE_BREATH-1.0-0.5,ENDERMAN_DEATH'

# Night開始
soundNightStart: 'LEVEL_UP-0.8-0.5,ZOMBIE_UNFECT-1.0-0.8,BLAZE_BREATH-1.0-0.5'

# Night終了
# リソースパックで、拍手＋イエエエェェェーーイ！ 音に変えるといいかも。
soundNightEnd: 'ENDERDRAGON_DEATH-0.4-2.0'

# プレイヤーが捕まったときの効果音
soundPlayerCaught: 'GHAST_SCREAM-1.0-0.5,FIREWORK_LARGE_BLAST-1.0-0.5'
