# ${project.name} v${project.version}
# @author     ucchy
# @license    LGPLv3
# @copyright  Copyright ucchy 2015


# メッセージの言語
lang: ja

# 最大参加人数。少なくとも5人以上に設定してください。
maxPlayers: 64

# ゲーム内の1時間を、実際の何秒にするか。
# 例えば90にすると、1時間進むのに90秒かかり、1つのNightに9分（540秒）かかります。
secondsOfOneHour: 90

# Foxyが、一晩で行動できる回数。0か、1から5が設定できます。
# 0を設定すると、1から5がランダムで選択されます。
foxyMovementPerNight: 3

# カスタムナイトの各キャラの移動速度。
# 各キャラの移動速度レベルを、0(ランダム)か、1から5で設定します。
customNightMoveSpeed:
  freddy: 4
  chica: 4
  bonnie: 4
  foxy: 3
