# ${project.name} v${project.version}
# @author     ucchy
# @license    LGPLv3
# @copyright  Copyright ucchy 2015


# =============== 共通設定 ===============

# メッセージの言語
lang: ja

# 最小参加人数。少なくとも2人以上に設定してください。
minPlayers: 2

# 最大参加人数。minPlayersの数値以上に設定してください。
maxPlayers: 64

# ゲーム内の1時間を、実際の何秒にするかを指定します。
# 例えば90にすると、1時間進むのに60秒かかり、1つのNightに6分（360秒）かかります。
secondsOfOneHour: 60

# Nightが終わって、次のNightが始まるまでの、インターバル。秒数で指定します。
secondsOfNightInterval: 15


# =============== 自動開始の設定 ===============

# 自動開始タイマー機能を使用するかどうかです。
# true = 使用する、false = 使用しない
autoStartTimer: false

# 自動開始タイマーを起動する人数です。
# 2 を設定したら、2人が参加した段階で自動開始タイマーが起動します。
autoStartTimerPlayerNum: 2

# 自動開始タイマーの秒数です。
# 15 を設定したら、自動開始タイマーが起動してから15秒後にゲームが開始します。
autoStartTimerSeconds: 15

# アリーナ設定が複数ある場合、自動で募集を開始するときに、
# ランダムにアリーナ設定を切り替えるかどうかを指定します。
autoStartTimerRandomArenaSwitch: true


# =============== Players陣営の設定 ===============

# 1秒あたりのバッテリー基本消費量
batteryDecreasePerSecond: 0.14

# 懐中電灯を使用しているときの1秒あたりのバッテリー消費量
batteryFlashLightPerSecond: 0.2

# レーダーを使用したときの1回あたりのバッテリー消費量
batteryRaderPerUse: 1.0

# シャッターを使用しているときの1秒あたりのバッテリー消費量
batteryShutterPerSecond: 0.67

# レーダーの索敵範囲。デフォルトは15マスです。
raderSearchingRange: 15

# プレイヤーのログアウト逃げ期限時間（秒）。
# もしプレイヤーがゲーム中にログアウトし、設定時間が過ぎた場合、そのプレイヤーは負けになります。
playerLogoutTrackingSeconds: 20


# =============== Freddy's陣営の設定 ===============

# Night1 の各キャラの移動速度。
# 各キャラの移動速度レベルを、-99(移動不可)か、-5から5で設定します。
# Foxyは普段は移動不可で、行動時間の時のみ、ここに設定した移動速度で移動できます。
# foxyMovementは、Foxyが一晩で行動できる回数です。-1か、0か、1から5が設定できます。
# fredbearMovementは、FredBearが一晩で高速行動できる回数です。-1か、0か、1から5が設定できます。
# -1を設定すると、そのNightは行動できません。0を設定すると、1から5がランダムで選択されます。
night1MoveSpeed:
  freddy: -99
  chica: -3
  bonnie: -3
  foxy: 1
  fredbear: -1
  foxyMovement: 1
  fredbearMovement: 1

# Night2 の各キャラの移動速度。
night2MoveSpeed:
  freddy: -99
  chica: -2
  bonnie: -2
  foxy: 1
  fredbear: -1
  foxyMovement: 1
  fredbearMovement: 1

# Night3 の各キャラの移動速度。
night3MoveSpeed:
  freddy: -1
  chica: -1
  bonnie: -1
  foxy: 2
  fredbear: 0
  foxyMovement: 2
  fredbearMovement: 2

# Night4 の各キャラの移動速度。
night4MoveSpeed:
  freddy: 0
  chica: 0
  bonnie: 0
  foxy: 3
  fredbear: 0
  foxyMovement: 3
  fredbearMovement: 2

# Night5 の各キャラの移動速度。
night5MoveSpeed:
  freddy: 1
  chica: 1
  bonnie: 1
  foxy: 3
  fredbear: 1
  foxyMovement: 3
  fredbearMovement: 2

# Night6 の各キャラの移動速度。
night6MoveSpeed:
  freddy: 2
  chica: 2
  bonnie: 2
  foxy: 4
  fredbear: 2
  foxyMovement: 4
  fredbearMovement: 3

# カスタムナイト(Night7)の各キャラの移動速度。
customNightMoveSpeed:
  freddy: 4
  chica: 4
  bonnie: 4
  foxy: 5
  fredbear: 3
  foxyMovement: 5
  fredbearMovement: 4

# Foxyが、一回の行動で移動可能な時間（秒）を指定します。
foxyMovementSeconds: 15

# Chicaが、威嚇をしてから、次の威嚇が可能になるまでの時間（秒）を指定します。
chicaThreatCooldownSeconds: 20

# FredBearが、高速行動アイテムを利用したときのスピード上昇量を指定します。
fredbearSpeedUp: 3


# =============== スコア設定 ===============

# プレイヤーがNightを勝ちのびたときに与えられるスコア
scorePlayerOverNight: 3

# Freddy's陣営が、プレイヤーを一人捕まえるたびに与えられるスコア
scoreAnimatronicsCatch: 1


# =============== 装備品の設定 ===============

# Freddy's陣営側の、プレイヤーの装備を変更します。見た目のみで、性能に変化はありません。
# 3Dリソースパックを利用する場合に、ご利用ください。
# アイテム表記は、こちらのリストから選んでください。
# https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html

armorContentsFreddy:
  helmet: 'LEATHER_HELMET'
  chestplate: 'LEATHER_CHESTPLATE'
  leggings: 'LEATHER_LEGGINGS'
  boots: 'LEATHER_BOOTS'
armorContentsChica:
  helmet: 'GOLD_HELMET'
  chestplate: 'GOLD_CHESTPLATE'
  leggings: 'GOLD_LEGGINGS'
  boots: 'GOLD_BOOTS'
armorContentsBonnie:
  helmet: 'DIAMOND_HELMET'
  chestplate: 'DIAMOND_CHESTPLATE'
  leggings: 'DIAMOND_LEGGINGS'
  boots: 'DIAMOND_BOOTS'
armorContentsFoxy:
  helmet: 'IRON_HELMET'
  chestplate: 'IRON_CHESTPLATE'
  leggings: 'IRON_LEGGINGS'
  boots: 'IRON_BOOTS'
armorContentsFredBear:
  helmet: 'LEATHER_HELMET'
  chestplate: 'LEATHER_CHESTPLATE'
  leggings: 'LEATHER_LEGGINGS'
  boots: 'LEATHER_BOOTS'


# =============== 効果音の設定 ===============

# 懐中電灯のオンオフ
soundUseFlashLight: 'CLICK'

# レーダーの使用
soundUseRader: 'IRONGOLEM_HIT-1.0-0.7'

# シャッターの使用
soundUseShutter: 'WITHER_SHOOT-1.0-1.0'

# Foxyの行動開始
soundFoxyMovement: 'ZOMBIE_REMEDY-1.0-1.0'

# Freddyの電力切れプレイヤーへのテレポート
# この効果音はテレポート先の近隣プレイヤーに流れます。
# リソースパックで、Freddyのオルゴール音に変えるといいかも。
soundFreddyTeleport: 'ENDERMAN_TELEPORT-1.0-0.8,BLAZE_BREATH-1.0-0.5,ENDERMAN_DEATH'

# Night開始
soundNightStart: 'LEVEL_UP-0.8-0.5,ZOMBIE_UNFECT-1.0-0.8,BLAZE_BREATH-1.0-0.5'

# Night終了
# リソースパックで、拍手＋イエエエェェェーーイ！ 音に変えるといいかも。
soundNightEnd: 'ENDERDRAGON_DEATH-0.4-2.0'

# プレイヤーが捕まったときの効果音
soundPlayerCaught: 'GHAST_SCREAM-1.0-0.5,FIREWORK_LARGE_BLAST-1.0-0.5'

# Chicaが威嚇するときの効果音
soundChicaThreat: 'GLASS,ZOMBIE_UNFECT-1.0-0.8,IRONGOLEM_DEATH-0.7-1.0-3'
